spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biologynet
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    show-sql: true
